version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ruamel-yaml
    versions:
    - 0.16.12
    - 0.16.13
    - 0.17.0
    - 0.17.2
  - dependency-name: urllib3
    versions:
    - 1.26.2
    - 1.26.3
